### ISSUE TITLE
Error case when run example

### ISSUE THREAD

**Issue by XiaochenCui** [mardix/flask-cloudy#15]
Traceback (most recent call last):
  File "/home/chenxiao/myproject/flask-cloudy/example/app.py", line 16, in <module>
    storage.init_app(app)
  File "/home/chenxiao/myproject/flask-cloudy/flask_cloudy.py", line 217, in init_app
    "directory or doesn't exist for LOCAL provider" % container)
OSError: Local Container (directory) './data' is not a directory or doesn't exist for LOCAL provider

**Comment by natarajan0007** [comment]
I am also getting same error.  Did you fixed the issue?@XiaochenCui  

@mardix  It works fine when i run the app standalone .When i deploy the code in IIS Enviroment i am getting error.

Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\dashboard\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "C:\inetpub\wwwroot\dashboard\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "C:\inetpub\wwwroot\dashboard\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File "C:\inetpub\wwwroot\dashboard\manage.py", line 1, in <module>
    from thermos import app,db
  File "C:\inetpub\wwwroot\dashboard\thermos\__init__.py", line 67, in <module>
    storage.init_app(app)
  File "c:\users\nataramu\appdata\local\programs\python\python37-32\lib\site-packages\flask_cloudy.py", line 242, in init_app
    "directory or doesn't exist for LOCAL provider" % container)
OSError: Local Container (directory) '//FC-PUN01-FS004//Data-Repository//Projects//217075-I-UK-N&T-POA//ITG//ITG 3rd Line Monthly Roster//' is not a directory or doesn't exist for LOCAL provider
